(specifications->manifest '("emacs"
			    "hunspell"
			    "hunspell-dict-en-au"
			    "sqlite"

                            ;; emacs packages
                            ;;
                            "emacs-diminish" 
                            "emacs-f"
                            "emacs-vertico"
			    "emacs-marginalia"
			    "emacs-evil"
			    "emacs-evil-collection"
			    "emacs-general"
			    "emacs-vterm"
			    "emacs-magit"
			    "emacs-pdf-tools"
			    "emacs-org-contrib"
			    "emacs-yasnippet"
			    "emacs-python-black"
			    "emacs-flycheck"

                            ;; latex
                            ;;
                            "texlive-latexmk"
                            "texlive-scheme-basic"
                            "texlive-collection-fontsrecommended"
                            "texlive-collection-latexrecommended"
                            "texlive-wrapfig"
                            "texlive-ulem"
                            "texlive-capt-of"
                            "texlive-latex"
                            "texlive-listings"
                            "texlive-beamer"
                            "texlive-pgf"
                            "texlive-biblatex"
                            "texlive-latexdiff"
                            "texlive-titling"
                            "texlive-datetime"
                            "texlive-fmtcount"
                            "texlive-titlesec"
                            "texlive-exam"
                            "texlive-gensymb"
                            "texlive-appendix"
                            "texlive-blindtext"
                            "texlive-wallpaper"
                            "texlive-sectsty"
                            "texlive-preprint"
                            "texlive-xifthen"
                            "texlive-ifmtarg"
                            "texlive-mdframed"
                            "texlive-zref"
                            "texlive-needspace"
                            "texlive-csquotes"
                            "texlive-threeparttable"
                            "texlive-adjustbox"
                            "texlive-vancouver"
                            "texlive-lastpage"
                            "texlive-standalone"

                            ;; python
                            ;;
                            "python"
			    "python-pylint" 
			    "python-tomli" 
			    "python-numpy"
			    "python-matplotlib"
                            "python-tornado"))
